# opentrons travis configuration

matrix:
  fast_finish: false
  include:
    - os: linux
      sudo: false
      language: python
      python: '3.6'
      env:
        LINT=true
        BUILD_APP=true
        BUILD_PD=true
        BUILD_COMPONENTS=true
        BUILD_API_DOCS=true
      addons:
        apt:
          sources: &common_sources
          packages: &common_packages
            - g++
            - gcc
            - icnsutils # electron-builder dependency
            - graphicsmagick # electron-builder dependency
            - xvfb

    - os: osx
      language: generic
      if: type != pull_request AND (tag IS present OR branch IN (master, edge))
      env:
        LINT=false
        BUILD_APP=true
        BUILD_PD=false
        BUILD_COMPONENTS=false
        BUILD_API_DOCS=false

cache:
  pip: true
  yarn: true
  directories:
    - $HOME/.pyenv
    - $HOME/Library/Caches/Homebrew

before_install:
  # source these scripts because they modify $PATH
  - source scripts/travis-env.sh
  - source scripts/travis-install.sh

install:
  - make -j 2 install

before_script:
  # Get all branches to allow comparison for mono-repo management tools
  - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch

script:
  - make test
  - if [[ $LINT = true ]]; then make lint; fi
  - if [[ $BUILD_COMPONENTS = true ]]; then make -C components build; fi
  - if [[ $BUILD_PD = true ]]; then make -C protocol-designer build; fi
  - if [[ $BUILD_APP = true ]]; then make -C app-shell dist-$APP_OS_TARGET; fi
  - if [[ $BUILD_API_DOCS = true ]]; then (make -C api docs > /dev/null); fi

after_success:
  - make coverage

deploy:
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    local-dir: api/docs/dist
    on:
        condition: $BUILD_API_DOCS = true
        repo: Opentrons/opentrons
        branch: edge

  # app deploy
  - provider: s3
    skip_cleanup: true
    # TODO(mc, 2018-03-26): use AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $OT_BUCKET_APP
    upload-dir: $OT_FOLDER_APP
    local-dir: $(pwd)/app-shell/dist/publish
    acl: public_read
    on:
      condition: $BUILD_APP = true
      repo: Opentrons/opentrons
      all_branches: true

  # protocol designer deploy
  - provider: s3
    # TODO(mc, 2018-03-26): use AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: opentrons-protocol-designer
    skip_cleanup: true
    local-dir: $(pwd)/protocol-designer/dist/
    upload-dir: $TRAVIS_BRANCH
    acl: public_read
    # TODO(mc, 2018-03-26): why is this region not default?
    region: us-west-2
    on:
      condition: $BUILD_PD = true
      repo: Opentrons/opentrons
      all_branches: true

  # components library deploy
  - provider: s3
    # TODO(mc, 2018-03-26): use AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: opentrons-components
    skip_cleanup: true
    local-dir: $(pwd)/components/dist/
    upload-dir: $TRAVIS_BRANCH
    acl: public_read
    # TODO(mc, 2018-03-26): why is this region not default?
    region: us-west-2
    on:
      condition: $BUILD_COMPONENTS = true
      repo: Opentrons/opentrons
      all_branches: true

env:
  global:
    - OT_BUILD: $TRAVIS_BUILD_NUMBER
    - OT_BRANCH: $TRAVIS_BRANCH
    - OT_TAG: $TRAVIS_TAG

    - OT_BUCKET_APP: opentrons-app
    - OT_FOLDER_APP: builds

    # GITHUB_TOKEN
    - secure: f/W7kN4gOvVpIanTQh9QtCwiXOk5UrRnUPo2ZU1Qk8zaFVbNj2za2A1xGKMqSyfZKw7guqIwTjWgc/aF9lxRtfU+5fkedJQdxDi5r7jZFxpqmpZOlhyXVY8WAWNqavEkefQInPlpHVAL8M2eV+Pi1cO9FsMhdyy/Wk7qA2nOiA8//9pFRB+0jgSbe1yqIF5DPyL0kbibd3EwmQvuQtnn25qqJXjneenhL6spflLCrnUjq1N/iOlcGd94eBUtk8RaBtMEjOb2D0Mb0DWKMsppoXg4/mZDus6s/PlmBwUJKNCuRtDiEUn5brE14q3OQh/FkDoXMRl69VND2mYp1LOeh5fgLSu6P+YToyHrh4lhXaRAul6l3JmXuoDC3k8hOAr8rPbtiwH7wGY2eRNv59vUejdXof4KHbAN6FTIH934tTe4uvBH79hRMoFY51pHRe6UiC39e/3hwl0pVKLjkV/40wfdEeYA7xhTZQVux+FAfk2krmggokxGEhbAQhWoyRX/wlH2XfEgassGskJ9SbuumNPNOLmEV9OOISFaXoYqVn+SPXy8mN1Pl2sLfaPFtnmmiY20t6yWsHsmfwi+41lv8n0vwCOGq521suDeNyiFhOH2AqG7xm6nHbIv+CiWt2ntKXgV233J17usvfr1zSK07PMDMlV2lvJx3CXj3hA4Yb4=

    # OT_APP_MIXPANEL_ID
    - secure: "T0h/KyXFRS4jsaor2sRLlKaUFxVmIH5LXArVLYi6I3Wz45SXvQuiH+gUic775rBLdpI8d+TgxCWyUPm1AJTCvCdaMr5PW/xyHeTT4qz0MKT1nThrO2Vi5cKWAUbZV6P8d8m9EBsJlvhgp7egLymS4K5zaotV07v6OK0qVJWiFo+Zj/ufQhQikIUaKOdNafKAqN4bSO/yqD6i9av/EOzkOJwIk2hnEMlCphZ/X2T81IXjw7toV0jjGL60tkL6lcULwDosrvJkb5+dr4AcUjwpb6tzexde2OfA7EyMN4BdIHXsAzKcqcxP0LVXoRqC2C2OyNITVHPci/r/kbqJOka9iGPn7BmUddjbhHb97nBygNDBZIS+U/W5nalO4ZLWe4RzgN85y5lFOdY9X0n8ZwkNwGKBxqueAdfmbPtkpYd5n0g9GMohRWO2wAb4ttY8Uw3x+OG75tmru37i6qO5Gl5VCo8ERIH8bAdEtzTB2Nna413Hm1ld4NmZFMGHfBL7scgyugAKoxgBebEIrTgtKQ6hBuVXWznS0E1bCoas9anR72UsXQol7MWxAmngv+We0ywBOG2qHRnKWwgUEp91R3OEIkH0ain9coPvX0e1mchvhuxiRvMlDZ9DU/narUpMol+/CslyHAMlRr8scNk2MAgNfRIhgEsrbbOrszVbgHtoFPE="

    # OT_APP_INTERCOM_ID
    - secure: "B+OLp0ZNWX6T9BFFGdNYA6vmXYJH0KXFGdyrEKHh0bFC4BnbPbbhN1SFp50Au+uMY1lzIhnihrkLpabie89N8HfHVuvTf27KDGP2vUrs7Vnnf+goSb2PrtcFcRNDjOM5bKQAWNfrjDVUBYkDWWL+zkS9ms6+mF+E8keCDGeMacPSus6NNK1v8+i9yK1/lJHYHxA353BkU73iP2SdrZ3IFuysEG8DVj9wBl7fXYOHrP2Dzw/ZQYzQOiagPYGAPoyMDcbr0Pnq1wu9sPADbPAA+UFOq0LfNTLDd8iP6EZuahwVIhldKBFOuT15YmbHG2c00Hepjl9V72d2FwnkXWcbKf/tgOrgCO+mDgYXtwE7rVfBQdhCZGgfxY7w8MTmNNm/WRrFhLBVvLpRGmVprIrA0fTJVUUo5O+YUHXuSAWwE2OPM3MfXj4Qdy656mTg6A/FWRuE1IZffhr/YhfcHiW6VG/W5t5wF5dzR1so4QILcL+aU2wfoHaFQ+c25ejoo7aPaY4D1bbQl0AtpQMJLtMSUH8X7xJGkVgc3mbwFdpvHNAhh2rhtOJtftwhTXSZ0WLfcJLl4Hj2F/6IqZj/DvTO5xMjuqdTigFVJzUSFdG6C61Af5C49v+ag9hqTHyQ59kOIFoKeyW4SPmqQIm7ZSVs1h3wCkmtZVOHWSV+n41JJ/I="

notifications:
  email:
    on_success: change
    on_failure: change
