language: python

matrix:
  # Set fast_finish to false to wait for OSX build to finish
  # We need both builds when we want to push an app update
  # Otherwise with fast_finish: true
  # the success of Linux build is enough for CI purposes
  fast_finish: true
  include:
    - os: linux
      sudo: false
      python: "3.5"
      env:
        - DEPLOY_DIR="linux"
      addons:
        apt:
          sources: &common_sources
          packages: &common_packages
            - g++
            - gcc
            - icnsutils # electron-builder dependency
            - graphicsmagick # electron-builder dependency
            - xvfb
    - os: osx
      language: generic
      env:
        - DEPLOY_DIR="mac"

# More: https://docs.travis-ci.com/user/caching/
cache:
  pip: true
  directories:
    - app/node_modules
    - $HOME/.pyenv
    - $HOME/.cache/brew
    - .nvm

before_install:
  - openssl aes-256-cbc -K $encrypted_f176ff9ac49f_key -iv $encrypted_f176ff9ac49f_iv -in .pypirc.enc -out $HOME/.pypirc -d

install:
  - source scripts/install-${TRAVIS_OS_NAME} # OS-specific installs
  - node --version
  - pip install pyyaml coveralls
  - cd api && make install && cd ..
  - cd app && make install && cd ..

script:
  - "export OT_TIME_SUFFIX=-$(date '+%Y-%m-%d_%H-%M')"
  - "export OT_BRANCH_SUFFIX=-${TRAVIS_BRANCH}"
  - "export OT_COMMIT_SUFFIX=-${TRAVIS_COMMIT:0:7}"
  - cd api && make test exe && cd ..
  - > # Make docs on linux only
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (cd api && make docs > /dev/null && cd ..) fi;
  - cd app && make -j 2 build test test-e2e && make package && cd ..
  # Clean up. This will leave only single-file build artifacts
  - find ./app/dist/** ! -name 'opentrons-v*' -exec rm -rf {} +

after_success:
  - cd api && coveralls && cd ..

# Deploy the build version in an S3 bucket
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ot-app-builds
    skip_cleanup: true
    local-dir: $(pwd)/app/dist
    upload-dir: $DEPLOY_DIR
    acl: public_read
    on:
      condition: $TRAVIS_TEST_RESULT = 0
      repo: Opentrons/opentrons
      all_branches: true

  # Publish API to PyPI and Anaconda
  - provider: script
    skip_cleanup: true
    script: cd api && make publish && cd ..
    on:
      # tags: true
      branch: master

env:
  global:
  - OT_NODE_VERSION: 6.11.5  # LTS Boron
  - ENCRYPTION_LABEL: c6cefc96bb2c
  - COMMIT_AUTHOR_EMAIL: sphinx@opentrons.com
  - secure: XBRwYt3Bowc3klVy6FyXIfeyOBzFzrzMwRJbIz54L8Ov7o2qV8l+5M16iyOy8O8C1qTFMVyCmW3K+xHPQaMstq7rPeVACwJ9VpyQciaDAWVujhyhuN94hU0YtmB1KtmPUHdYCuD25eL5HJ2GDjmYqq/XUYyuX67rrPxT5b5z7Yf4kdkPyBIa5c+KyklYmJLdHGBJUuOfM7qvxOo7nlMyzU+LfgvtqM15g7eQIvXGDydi59lT6FOpW9J9h4Z2Nwmc2lHjxCxi5SI2NIR7K5DsqjtRi0eMcr1m098CA/T1Oh4c5qlG8Uoi+KpOcfcTuAP3VSFdbMgRFmtQ3gwJ71ZPB7GeqvLXSgriACl12n0uienOYrb6/X1Nujsl7Pxjh8KMiIBRcX2/46ecyeN+gP+6u9ic5mPRMFky1e2dqbbUTIeAw7397ufvtIPb0qW4mUMdu4NMkiRg01aF5ZmgVMXvnvQm/xyF+SC0Qtj9uOjZUzsj5DVnLuLHekP3OYpxRzFFzpjBZmdwCsEtwHH8PmuG/owa6Jmf4aXN50dgCL6oRPjWoH213jOdjplGI7ZMZXAigGrN9sT9Om67ZWNuN/TYgy+K3QIp2ELC6MmpJNuH9n8M1pCtynitSyvuW5YhG/j7VH3TKDogID3FOgPYAjfC0EshHt+Kl2GddaR3bpCa3XA=

notifications:
  email:
    on_success: change
    on_failure: change
