language: python

matrix:
  # Set fast_finish to false to wait for OSX build to finish
  # We need both builds when we want to push an app update
  # Otherwise with fast_finish: true
  # the success of Linux build is enough for CI purposes
  fast_finish: true
  include:
    - os: linux
      sudo: false
      python: "3.5"
      env:
        - PUBLIC_REPO="$(git remote -v | tail -n 1 | sed s/.*opentrons\.git.*/true/g)"
      addons:
        apt:
          sources: &common_sources
          packages: &common_packages
            - g++
            - gcc
            - icnsutils # electron-builder dependency
            - graphicsmagick # electron-builder dependency
            - xvfb

# More: https://docs.travis-ci.com/user/caching/
cache:
  pip: true
  directories:
    - $HOME/.pyenv
    - $HOME/.cache/brew
    # location of npm cache - preferable to cache this rather than node_modules
    # because we have one cache for all npm projects plus caching node_modules
    # can cause issues with native deps
    - $HOME/.npm

before_install:
  - >  # load keys needed to publish to pypa only when building from public repo
    if [[ "$PUBLIC_REPO" == "true" ]]; then (openssl aes-256-cbc -K $encrypted_f176ff9ac49f_key -iv $encrypted_f176ff9ac49f_iv -in .pypirc.enc -out $HOME/.pypirc -d) fi;

install:
  - source scripts/install-${TRAVIS_OS_NAME} # OS-specific installs
  - node --version
  - make install

script:
  - "export OT_TIME_SUFFIX=-$(date '+%Y-%m-%d_%H-%M')"
  - "export OT_BRANCH_SUFFIX=-${TRAVIS_BRANCH}"
  - "export OT_COMMIT_SUFFIX=-${TRAVIS_COMMIT:0:7}"
  # TODO(mc, 2017-08-28): use top level `make test`
  - make -C api test
  - make -C api lint
  # TODO (artyom 20171030): bring this back once the API is stable and documentation is fixed
  # - > # Make docs on linux only
  #   if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (make -C api docs > /dev/null) fi;
  # TODO(mc, 2017-08-28): use top level `make test`
  - make -C app package test && make -C app dist-posix
  # Clean up. This will leave only single-file build artifacts
  - find ./app/dist/** ! -name 'opentrons-v*' -exec rm -rf {} +
  # protocol designer
  # TODO(ian, 2017-11-06): use makefile
  - make -C protocol-designer install test build
  # components library
  # TODO(mc, 2017-12-07): seriously figure out that top-level Makefile
  - make -C components test

after_success:
  - make coverage

# Deploy the build version in an S3 bucket
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ot-app-builds
    skip_cleanup: true
    local-dir: $(pwd)/app/dist
    upload-dir: ci-builds
    acl: public_read
    on:
      condition: $TRAVIS_TEST_RESULT = 0
      repo: Opentrons/opentrons
      all_branches: true

  # Publish API to PyPI and Anaconda
  - provider: script
    skip_cleanup: true
    script: make -C api publish
    on:
      tags: true

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: opentrons-protocol-designer
    skip_cleanup: true
    local-dir: $(pwd)/protocol-designer/dist/
    upload-dir: $TRAVIS_BRANCH
    acl: public_read
    region: us-west-2
    on:
      condition: $TRAVIS_TEST_RESULT = 0
      repo: Opentrons/opentrons
      all_branches: true

env:
  global:
  - OT_PYTHON_VERSION: '3.5.3'
  - ENCRYPTION_LABEL: c6cefc96bb2c
  - COMMIT_AUTHOR_EMAIL: sphinx@opentrons.com
  - secure: XBRwYt3Bowc3klVy6FyXIfeyOBzFzrzMwRJbIz54L8Ov7o2qV8l+5M16iyOy8O8C1qTFMVyCmW3K+xHPQaMstq7rPeVACwJ9VpyQciaDAWVujhyhuN94hU0YtmB1KtmPUHdYCuD25eL5HJ2GDjmYqq/XUYyuX67rrPxT5b5z7Yf4kdkPyBIa5c+KyklYmJLdHGBJUuOfM7qvxOo7nlMyzU+LfgvtqM15g7eQIvXGDydi59lT6FOpW9J9h4Z2Nwmc2lHjxCxi5SI2NIR7K5DsqjtRi0eMcr1m098CA/T1Oh4c5qlG8Uoi+KpOcfcTuAP3VSFdbMgRFmtQ3gwJ71ZPB7GeqvLXSgriACl12n0uienOYrb6/X1Nujsl7Pxjh8KMiIBRcX2/46ecyeN+gP+6u9ic5mPRMFky1e2dqbbUTIeAw7397ufvtIPb0qW4mUMdu4NMkiRg01aF5ZmgVMXvnvQm/xyF+SC0Qtj9uOjZUzsj5DVnLuLHekP3OYpxRzFFzpjBZmdwCsEtwHH8PmuG/owa6Jmf4aXN50dgCL6oRPjWoH213jOdjplGI7ZMZXAigGrN9sT9Om67ZWNuN/TYgy+K3QIp2ELC6MmpJNuH9n8M1pCtynitSyvuW5YhG/j7VH3TKDogID3FOgPYAjfC0EshHt+Kl2GddaR3bpCa3XA=

notifications:
  email:
    on_success: change
    on_failure: change
