language: python

matrix:
  # Set fast_finish to false to wait for OSX build to finish
  # We need both builds when we want to push an app update
  # Otherwise with fast_finish: true
  # the success of Linux build is enough for CI purposes
  fast_finish: true
  include:
    - os: linux
      # Trying container environment
      sudo: false
      # sudo: required
      # dist: trusty
      python: "3.5"  # TODO: revisit...
      env: OPENTRONS_APP_UPLOAD_DIR=linux
      addons:
        apt:
          sources: &common_sources
          packages: &common_packages
            - g++
            - gcc
            - icnsutils # electron-builder dependency
            - graphicsmagick # electron-builder dependency
            - xvfb

    - os: osx
      language: generic
      env: OPENTRONS_APP_UPLOAD_DIR=mac

cache:
  apt: true
  directories:
    - app-src/node_modules
    - app-shell/node_modules
    - app-shell/app/node_modules
    # - $HOME/.electron
    # - pip
    # - $HOME/.cache/pip3
    - $HOME/.cache/our-brew

before_install:
  - openssl aes-256-cbc -K $encrypted_f176ff9ac49f_key -iv $encrypted_f176ff9ac49f_iv -in .pypirc.enc -out $HOME/.pypirc -d
  - ./app-shell/scripts/travis.sh pre-install

install:
  - python --version
  - python3 --version
  - git remote set-branches --add origin $STABLE_BRANCH
  - git fetch
  -  ./scripts/with-nodenv-linux "make app"
  - make api-exe
  -  ./scripts/with-nodenv-linux "make app-shell"

script:
  - echo "Skipping Travis scripts"

# Deploy the build version in an S3 bucket
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ot-app-builds
    skip_cleanup: true
    local-dir: app-shell/releases
    upload-dir: $OPENTRONS_APP_UPLOAD_DIR
    acl: public_read
    on:
      repo: OpenTrons/opentrons-api
      all_branches: true

  # Publish API to PyPI and Anaconda
  - provider: script
    skip_cleanup: true
    script: api/scripts/publish.sh
    on:
      tags: true

env:
  global:
  - ENCRYPTION_LABEL: c6cefc96bb2c
  - COMMIT_AUTHOR_EMAIL: sphinx@opentrons.com
  - secure: XBRwYt3Bowc3klVy6FyXIfeyOBzFzrzMwRJbIz54L8Ov7o2qV8l+5M16iyOy8O8C1qTFMVyCmW3K+xHPQaMstq7rPeVACwJ9VpyQciaDAWVujhyhuN94hU0YtmB1KtmPUHdYCuD25eL5HJ2GDjmYqq/XUYyuX67rrPxT5b5z7Yf4kdkPyBIa5c+KyklYmJLdHGBJUuOfM7qvxOo7nlMyzU+LfgvtqM15g7eQIvXGDydi59lT6FOpW9J9h4Z2Nwmc2lHjxCxi5SI2NIR7K5DsqjtRi0eMcr1m098CA/T1Oh4c5qlG8Uoi+KpOcfcTuAP3VSFdbMgRFmtQ3gwJ71ZPB7GeqvLXSgriACl12n0uienOYrb6/X1Nujsl7Pxjh8KMiIBRcX2/46ecyeN+gP+6u9ic5mPRMFky1e2dqbbUTIeAw7397ufvtIPb0qW4mUMdu4NMkiRg01aF5ZmgVMXvnvQm/xyF+SC0Qtj9uOjZUzsj5DVnLuLHekP3OYpxRzFFzpjBZmdwCsEtwHH8PmuG/owa6Jmf4aXN50dgCL6oRPjWoH213jOdjplGI7ZMZXAigGrN9sT9Om67ZWNuN/TYgy+K3QIp2ELC6MmpJNuH9n8M1pCtynitSyvuW5YhG/j7VH3TKDogID3FOgPYAjfC0EshHt+Kl2GddaR3bpCa3XA=

notifications:
  email:
    on_success: change
    on_failure: change

after_success: cd api && coveralls && cd ..
