# We are using the iOS build system to create Mac OS X python builds
language: objective-c
# osx_image: beta-xcode6.3
os:
  - osx

before_install:
  # OS extra info
  - uname -a
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"

  # Update brew
  - brew update

  # Install node.js
  - brew install nvm
  - mkdir ~/.nvm && export NVM_DIR=~/.nvm && source $(brew --prefix nvm)/nvm.sh && nvm alias default 6.0.0
  - echo "$(brew --prefix nvm)/nvm.sh" >> ~/.bashrc
  - nvm install 6.0.0
  - nvm use 6.0.0
  - node --version
  - npm --version
  - npm install

  # Install Python 2 and 3 with pip and check versions
  - brew tap drolando/homebrew-deadsnakes
  - brew install python34
  - brew link --overwrite python34
  - python3.4 --version
  - python3.4 -c "import struct; print(struct.calcsize('P') * 8)"
  - python --version
  - echo $PATH

  # Install Python packages (built with Python 3)
  - pip3.4 install pyinstaller
  - pyinstaller --version
  - pip3.4 install -r requirements.txt
  - python3.4 -m unittest


install:
  - node --version
  - npm --version
  - npm install && cd app && npm install && cd ..  # Hack until instapp-app-deps works on travis
  - npm i -g mocha
  - npm run unit
  - npm run release:mac
  - mocha --timeout 60000 test/integration_test.js
  - ls dist/mac
  - ls releases

# Deploy the build version in an S3 bucket
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: ot-app-builds
  skip_cleanup: true
  local-dir: releases
  upload-dir: mac
  acl: public_read
  on:
    repo: OpenTrons/robot_frontend_v2
    all_branches: true

notifications:
  email:
    on_success: change
    on_failure: change
