# opentrons platform appveyor config
#   Note: if build get stucks, you can use RDP to diagnose
#   https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

image: Visual Studio 2015

environment:
  # ensure Python 3.7 is first in path
  PATH: 'C:\Python37;C:\Python37\Scripts;%PATH%'
  # GNU make
  MAKE: C:\MinGW\bin\mingw32-make.exe

  # publish configuration
  OT_APP_DEPLOY_BUCKET: opentrons-app
  OT_APP_DEPLOY_FOLDER: builds

  OT_APP_MIXPANEL_ID:
    secure: W9ZdkT5jR5zZwQm1PMRzDNSZ1qFizfqGMIYv5hyGXPhpbzOPtyAlbJYfQMJ1Y+H+

  OT_APP_INTERCOM_ID:
    secure: BF0x/zKj1kHOnoHWLeCQXA==

init:
  # set vars in ps scripts because cmd is terrible at undefined vars
  - ps: $env:OT_TAG = $env:APPVEYOR_REPO_TAG_NAME
  - ps: $env:OT_BUILD = $env:APPVEYOR_BUILD_NUMBER
  - ps: $env:OT_BRANCH = $env:APPVEYOR_REPO_BRANCH

platform: x64

cache:
  - "%LOCALAPPDATA%\\Yarn"

install:
  # read node version from the first line of .nvmrc
  - ps: $env:nodejs_version = Get-Content -Path .nvmrc
  - ps: Install-Product node $env:nodejs_version x64
  # install dev dependencies
  - cmd: '%MAKE% -j 2 setup'
  # TODO(mc, 2019-09-09): remove this workaround when this issue is fixed:
  # https://github.com/electron-userland/electron-builder/issues/4092
  - cmd: 'yarn add -DW electron-builder@21.1.2'

# do not run MSBuild
build: false

# do not run automatic test discovery
test: off

build_script:
  - cmd: '%MAKE% test-windows'
  # build app
  - cmd: '%MAKE% -C app-shell dist-win'

after_build:
  - ps: Get-ChildItem .\app-shell\dist\publish\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName App}

deploy:
  - provider: S3
    # TODO(mc, 2018-03-26): use AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY
    access_key_id: $(AWS_ACCESS_KEY)
    secret_access_key: $(AWS_SECRET_KEY)
    bucket: $(OT_APP_DEPLOY_BUCKET)
    folder: $(OT_APP_DEPLOY_FOLDER)
    set_public: true
    artifact: App
