image: Visual Studio 2015

environment:
  BASH: C:\cygwin64\bin\bash
  PYTHON: c:\Python35 # No trailing backslash
  CYG_PYTHON_PATH: /cygdrive/c/Python35:/cygdrive/c/Python35/Scripts # Need to override /usr/bin

platform: x64

cache:
  - app\node_modules        # local npm modules
  - '%APPDATA%\npm-cache'   # npm cache
    
init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH% # Activate Python 3.5
  - git config --global core.autocrlf false # don't convert LFs to CRLFs since we are running Cygwin
  # Start RDP server to watch the build
  # https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# Keep RDP server to see at what happened if the build got stuck
# Uncomment this to debug a stuck build through RDP:
# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: Install-Product node 6.11.0 x64
  - '%BASH% -lc "export PATH=$CYG_PYTHON_PATH:$PATH && cd $APPVEYOR_BUILD_FOLDER/api && make install"'
  - '%BASH% -lc "cd $APPVEYOR_BUILD_FOLDER/app && make install"'

build: false # No need to run MSBuild

build_script:
  - '%BASH% -lc "export PATH=$CYG_PYTHON_PATH:$PATH && cd $APPVEYOR_BUILD_FOLDER/api && make test"'
  # Note: we are not running test-e2e on Windows due to problems with ChromeDriver
  - '%BASH% -lc "cd $APPVEYOR_BUILD_FOLDER && source scripts/env-vars-appveyor && make -C app package test && make -C app dist-win"'
  - >
    %BASH% -lc "cd $APPVEYOR_BUILD_FOLDER/app/dist/win && ls -la . && find ./** ! -name 'opentrons-v*' -exec rm -rf {} + && ls -la ."

before_deploy:
  - ps: Get-ChildItem .\app\dist\win | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName OTAppWin}

deploy:
  - provider: S3
    access_key_id: $(AWS_ACCESS_KEY)
    secret_access_key: $(AWS_SECRET_KEY)
    bucket: ot-app-builds
    set_public: true
    folder: ci-builds
    artifact: OTAppWin
