[tool.isort]
profile = "black"
skip_glob = ["files/*"]
[tool.black]
target-version = ['py310']
exclude = '(\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|_build|build|dist)'
[tool.mypy]
strict = true
follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
exclude = "__init__.py"
[mypy-selenium]
ignore_missing_imports = true
