[tool.poetry]
name = "notify-server"
version = "0.1.0"
description = ""
authors = ["amit lissack <amit@opentrons.com>"]

[tool.pytest.ini_options]
markers = ["env_var: used in test_settings"]

[tool.poetry.dependencies]
python = "^3.7"
pyzmq = "^19.0.2"
pydantic = "1.4"

[tool.poetry.dev-dependencies]
pytest = "^6.1"
pytest-watch = "^4.2.0"
pytest-cov = "^2.10.1"
mypy = "^0.790"
flake8 = "^3.8.4"
flake8-docstrings = "^1.5.0"
flake8-annotations = "^2.4.1"
mock = "^4.0.2"
<<<<<<< HEAD
pytest-asyncio = "^0.14.0"
=======
poetry-setup = "^0.3.6"
>>>>>>> 2cb46aa0f... add poetry-setup which generates setup.py from poetry project.

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
