# Run tests, build the app, and deploy it cross platform

name: 'App test, build, and deploy'

on:
  push:
    paths:
      - 'app/**/*'
      - 'app-shell/**/*'
      - 'components/**/*'
      - 'shared-data/**/*'
      - 'webpack-config/**/*'
      - 'discovery-client/**/*'
      - '*.js'
      - '*.json'
      - 'yarn.lock'
      - '.github/workflows/app-test-build.yaml'
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    paths:
      - 'app/**/*'
      - 'app-shell/**/*'
      - 'components/**/*'
      - 'shared-data/**/*'
      - 'webpack-config/**/*'
      - 'discovery-client/**/*'
      - '*.js'
      - '*.json'
      - 'yarn.lock'
  workflow_dispatch:

env:
  CI: true
  OT_APP_DEPLOY_BUCKET: opentrons-app
  OT_APP_DEPLOY_FOLDER: builds-actions  # Not the actual deploy target - change when we cut over

jobs:
  test:
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    name: 'opentrons app js tests'
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v1'
        with:
          node-version: '12'
      - name: 'Cache node_modules'
        uses: 'actions/cache@v2'
        id: js-cache
        with:
          path: '**/node_modules'
          key: node_modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: 'set complex environment variables'
        run: |
          echo ::set-env name=OT_BRANCH::$(echo ${{ github.ref }} | sed -E -e "s/^\/?refs\/(heads|pull)\///")
          echo ::set-env name=OT_TAG::$(echo ${{ github.ref }} | sed -E -e "s/^\/?refs\/:tags\///" | grep ^v)
          echo ::set-env name=OT_BUILD::$(expr 10000 + ${{ github.run_number }})
      - name: 'setup-js'
        run: 'make setup-js'
      - name: 'test relevant packages'
        run: |
          yarn jest --coverage=true --ci=true --testPathIgnorePatterns /labware-.*/ /protocol-.*/
      - if: github.event_name != 'pull_request'
        name: 'build app'
        run: |
          echo OT_BRANCH: ${OT_BRANCH}
          echo OT_TAG: ${OT_TAG}
          echo OT_BUILD: ${OT_BUILD}
          make -C app-shell dist-${{ matrix.os }}
      - if: github.event_name != 'pull_request'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_APP_DEPLOY_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_APP_DEPLOY_SECRET }}
        name: 'deploy'
        run: aws s3 sync --region=us-east-1 --acl=public-read app-shell/dist/publish s3://${OT_APP_DEPLOY_BUCKET}/${OT_APP_DEPLOY_FOLDER}
