# This workflow runs lint on pull requests that touch anything in the app-testing directory

name: 'app-testing lint'

on:
  pull_request:
    paths:
      - 'app-testing/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: 'app-testing lint'
    timeout-minutes: 5
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout opentrons repo
        uses: 'actions/checkout@v3'

      - name: Setup Python
        uses: 'actions/setup-python@v4'
        with:
          python-version: '3.12'
          cache: 'pipenv'
          cache-dependency-path: app-testing/Pipfile.lock
      - name: Install Pipenv
        run: pip install -U pipenv
      - name: Pipenv Install
        id: install
        working-directory: ./app-testing
        run: make setup
      - name: black-check
        if: always() && steps.install.outcome == 'success' || steps.install.outcome == 'skipped'
        working-directory: ./app-testing
        run: make black-check
      - name: ruff
        if: always() && steps.install.outcome == 'success' || steps.install.outcome == 'skipped'
        working-directory: ./app-testing
        run: make ruff-check
      - name: mypy
        if: always() && steps.install.outcome == 'success' || steps.install.outcome == 'skipped'
        working-directory: ./app-testing
        run: make mypy
