# Run tests and build the app cross-platform

name: 'App test and build'

on:
  push:
    paths:
      - 'app/**/*'
      - 'app-shell/**/*'
      - 'components/**/*'
      - 'shared-data/**/*'
      - 'webpack-config/**/*'
      - 'discovery-client/**/*'
      - '*.js'
      - '*.json'
      - 'yarn.lock'
      - '.github/workflows/app-test-build.yaml'
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    paths:
      - 'app/**/*'
      - 'app-shell/**/*'
      - 'components/**/*'
      - 'shared-data/**/*'
      - 'webpack-config/**/*'
      - 'discovery-client/**/*'
      - '*.js'
      - '*.json'
      - 'yarn.lock'
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  CI: true

jobs:
  test:
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    name: 'opentrons app js tests'
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v1'
        with:
          node-version: '12'
      - name: 'Cache node_modules'
        uses: 'actions/cache@v2'
        id: js-cache
        with:
          path: '**/node_modules'
          key: 'node_modules-${{ runner.os }}-${{ hashFiles("yarn.lock") }}'
      - name: 'set complex environment variables'
        run: |
          echo ::set-env name=OT_BRANCH::$(echo ${{ github.ref }} | sed -e "s/^\/\?refs\/\(heads\|pull\)\///")
          echo ::set-env name=OT_TAG::$(echo ${{ github.ref }} | sed -e "s/^\/\?refs\/:tags\///" | grep ^v)
          echo ::set-env name=OT_BUILD::$(expr 10000 + ${{ github.run_number }})
      - name: 'setup-js'
        run: 'make setup-js'
      - name: 'test relevant packages'
        run:
          yarn jest --coverage=true --ci=true --testPathIgnorePatterns labware-.* protocol-.*
      - if: github.event_name != 'pull_request'
        name: 'build app'

        run: |
          echo OT_BRANCH: ${OT_BRANCH}
          echo OT_TAG: ${OT_TAG}
          echo OT_BUILD: ${OT_BUILD}
          make -C app-shell dist-${{ matrix.os }}
