# This workflow builds API docs when either:
#
# * A commit is tagged like "docs@foo".
#
# * Someone pushes, to any branch, a commit that touches any of:
#   * The parts of the api/ project that are used by the docs.
#   * The docs source themselves;
#   * The CI/makefile tooling used to build the docs.


name: 'API docs build'

on:
  push:
    tags:
      - 'docs@*'
    branches:
      # We don't want to do any filtering based on branch name.
      # But because we specified `tags`, we need to specify `branches` too,
      # or else GitHub will only run this workflow for tag matches
      # and not for path matches.
      - '**'
    paths:
      - 'api/**'
      - '.github/workflows/docs-build.yaml'
      - '.github/actions/python/**'
      - '.github/actions/webstack/deploy-to-sandbox/**'
      - '.github/workflows/utils.js'
  workflow_dispatch:


defaults:
  run:
    shell: bash

jobs:
  build:
    name: opentrons documentation build
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v1'
        with:
          node-version: '14'
      - uses: 'actions/setup-python@v2'
        with:
          python-version: '3.7'
      - uses: './.github/actions/python/setup'
        with:
          project: 'api'
      - name: 'set complex environment variables'
        uses: actions/github-script@v3.1
        with:
          script: |
            const { buildComplexEnvVars, } = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/utils.js`)
            buildComplexEnvVars(core, context)
      - name: 'Setup Docs'
        run: sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended libsystemd-dev latexmk texlive-lang-greek
      - name: 'Build docs'
        run: |
          make -C api docs
      - name: 'Deploy docs to sandbox'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_SANDBOX_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SANDBOX_SECRET }}
        uses: './.github/actions/webstack/deploy-to-sandbox'
        with:
          domain: 'docs.opentrons.com'
          distPath: './api/docs/dist'
          destPrefix: ${{ env.OT_BRANCH }}
