name: 'hardware-testing testing protocols'

on:
  # Run on any change to the api directory
  pull_request:
    paths:
      - 'api/**'
      - 'hardware-testing/**'
      - 'Makefile'
  push:
    paths:
      - 'api/**'
      - 'hardware-testing/**'
      - 'Makefile'
      - '.github/workflows/hardware-testing-protocols.yaml'
    branches:
      - 'edge'
      - 'release'
      - '*hotfix*'
  create:
    tags:
      - 'v*'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.ref_name != 'edge' || github.run_id}}-${{ github.ref_type != 'tag' || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint-test:
    name: 'hardware-testing protocols'
    timeout-minutes: 20
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Checkout opentrons repo
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: 'actions/setup-node@v3'
        with:
          node-version: '12'

      - name: Setup Python
        uses: 'actions/setup-python@v4'
        with:
          python-version: '3.10'

      - name: Setup Project
        uses: './.github/actions/python/setup'
        with:
          project: 'hardware-testing'

      - name: Test-Integration
        run: make -C hardware-testing test-integration
