# This workflow runs test and lint on branch pushes that touch the
# hardware project or its dependencies

name: 'hardware lint/test'

on:
  # Most of the time, we run on pull requests, which lets us handle external PRs
  push:
    paths:
      - 'Makefile'
      - 'hardware/**'
      - 'scripts/**/*.mk'
      - 'scripts/**/*.py'
      - '.github/workflows/hardware-lint-test.yaml'
      - '.github/actions/python/**'
    branches:
      - 'edge'
      - 'release'
    tags-ignore:
      - '*'
  pull_request:
    paths:
      - 'Makefile'
      - 'hardware/**'
      - 'scripts/**/*.mk'
      - 'scripts/**/*.py'
      - '.github/workflows/hardware-lint-test.yaml'
      - '.github/actions/python/**'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.ref_name != 'edge' || github.run_id}}-${{ github.ref_type != 'tag' || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint-test:
    name: 'hardware package linting and tests'
    timeout-minutes: 30
    runs-on: 'ubuntu-22.04'
    steps:
      - name: Checkout opentrons repo
        uses: 'actions/checkout@v3'
      - uses: './.github/actions/python/setup-all-environments'

      # TODO(amit, 2022-03-08): Enable once ot3 emulation is ready
      #      - name: Setup SocketCan
      #        run: |
      #          sudo apt-get update
      #          sudo apt-get install linux-modules-extra-$(uname -r)
      #          sudo modprobe vcan
      #
      #      - name: Run OT-3 Emulator
      #        uses: Opentrons/opentrons-emulation@v1.3
      #        with:
      #          ot3-firmware-commit-id: latest
      #          modules-commit-id: latest

      - name: Lint
        run: make -C hardware lint

      - name: Test
        run: make -C hardware test-cov
      # TODO(amit, 2022-03-08): Enable once ot3 emulation is ready
      #        env:
      #          CAN_CHANNEL: vcan0
      #        run: make -C hardware test-with-emulator

      - name: Code Coverage
        uses: 'codecov/codecov-action@v3'
        with:
          files: ./hardware/coverage.xml
          flags: hardware
