# This workflow runs test and lint on branch pushes that touch the
# notify-server project or its dependencies

name: 'Notify server lint/test'

on:
  # Most of the time, we run on pull requests, which lets us handle external PRs
  push:
    paths:
      - 'Makefile'
      - 'notify-server/**/*'
      - '.github/workflows/notify-server-lint-test.yaml'
      - 'api/**/*'
      - 'hardware/**/*'
      - 'scripts/**/*.mk'
      - 'scripts/**/*.py'
      - '.github/actions/python/**/*'
    branches:
      - 'edge'
      - 'release'
      - '*hotfix*'
    tags-ignore:
      - '*'
  pull_request:
    paths:
      - 'Makefile'
      - 'notify-server/**/*'
      - 'api/**/*'
      - 'hardware/**/*'
      - 'scripts/**/*.mk'
      - 'scripts/**/*.py'
      - '.github/actions/python/**/*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.ref_name != 'edge' || github.run_id}}-${{ github.ref_type != 'tag' || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint-test:
    name: 'notify server package linting and tests'
    timeout-minutes: 20
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0
      - uses: 'actions/setup-node@v3'
        with:
          node-version: '21'
      - uses: 'actions/setup-python@v4'
        with:
          python-version: '3.7'

      - uses: './.github/actions/python/setup'
        with:
          project: 'notify-server'
      - name: Lint
        run: make -C notify-server lint
      - name: Test
        run: make -C notify-server test-cov
      - name: 'Upload coverage report'
        uses: 'codecov/codecov-action@v3'
        with:
          files: ./notify-server/coverage.xml
          flags: notify-server
