# This workflow runs test and lint on branch pushes that touch the
# notify-server project or its dependencies

name: 'Notify server lint/test'

on:
  # Most of the time, we run on pull requests, which lets us handle external PRs
  push:
    paths:
      - 'Makefile'
      - 'notify-server/**'
      - '.github/workflows/notify-server-lint-test.yaml'
      - '.github/actions/python/**'
    tags-ignore:
      - '*'
  pull_request:
    paths:
      - 'Makefile'
      - 'notify-server/**'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  lint-test:
    name: 'notify server package linting and tests'
    timeout-minutes: 20
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v1'
        with:
          node-version: '12'
      - uses: 'actions/setup-python@v2'
        with:
          python-version: '3.7'

      - uses: './.github/actions/python/setup'
        with:
          project: 'notify-server'
      - name: Lint
        run: make -C notify-server lint
      - name: Test
        run: make -C notify-server test
      - name: 'Upload coverage report'
        uses: 'codecov/codecov-action@v2'
        with:
          files: ./notify-server/coverage.xml
          flags: notify-server
