# This workflow runs test and lint on pull requests that touch the
# robot-server project or its dependencies

name: 'Robot server pull requests'

on:
  # Most of the time, we run on pull requests, which lets us handle external PRs
  pull_request_target:
    paths:
      - 'api/**'
      - 'Makefile'
      - 'shared-data/*/**'
      - '!shared-data/js/**'
      - 'robot-server/**'
  # The pull_request_target context, though, runs the workflow in the base
  # branch. That means we can't test workflow/action changes in pull requests
  # there. So we can instead have a very limited on-push hook that only fires
  # when github ci config is changed.
  push:
    branches-ignore: # ignore any release- or edge-related thing (handled elsewhere)
      - 'edge'
      - 'master'
      - 'chore_release-**'
      - 'chore_bump-**'
    tags-ignore:
      - '*'
    paths:
      - '.github/workflows/robot-server-pull-request.yaml'
      - '.github/actions/python/**'

defaults:
  run:
    shell: bash

jobs:
  lint-test:
    name: robot server package linting and tests
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v1'
        with:
          node-version: '12'
      - uses: 'actions/setup-python@v2'
        with:
          python-version: '3.7'

      - uses: './.github/actions/python/setup'
        with:
          project: 'robot-server'
      - name: Lint
        run: make -C robot-server lint
      - name: Test
        run: make -C robot-server test
