# Run tests for step generation

name: 'Step generation test'

on:
  pull_request:
    paths:
      - 'step-generation/**'
      - 'shared-data/**'
      - 'webpack-config/**'
      - 'package.json'
      - '.github/workflows/step-generation-test.yaml'
  push:
    paths:
      - 'step-generation/**'
      - 'shared-data/**'
      - 'webpack-config/**'
      - 'package.json'
      - '.github/workflows/step-generation-test.yaml'
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.ref_name != 'edge' || github.run_id}}-${{ github.ref_type != 'tag' || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CI: true

jobs:
  js-unit-test:
    name: 'step generation unit tests'
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 30
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'actions/setup-node@v3'
        with:
          node-version: '18.19.0'
      - name: 'install udev for usb-detection'
        run: sudo apt-get update && sudo apt-get install libudev-dev
      - name: 'setup-js'
        run: |
          npm config set cache ./.npm-cache
          make setup-js
      - name: 'run step generation unit tests'
        run: make -C step-generation test-cov
      - name: 'Upload coverage report'
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          flags: step-generation
