# This workflow runs tests and lint on non-release branches pushed that alter
# the update-server subpackage

name: 'Update Server test/lint'

on:
  push:
    paths:
      - 'update-server/**'
      - 'Makefile'
      - '.github/workflows/update-server-lint-test.yaml'
      - '.github/actions/python/**'
    branches-ignore: # ignore any release-related thing (handled elsewhere)
      - 'release'
      - 'chore_release-*'
    tags-ignore:
      - '*'
  pull_request:
    paths:
      - 'update-server/**'
      - 'Makefile'
      - '.github/workflows/update-server-lint-test.yaml'
      - '.github/actions/python/**'
    branches-ignore: # ignore any release-related thing (handled elsewhere)
      - 'release'
      - 'chore_release-*'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: 'update server linting'
    timeout-minutes: 10
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v1'
        with:
          node-version: '12'
      - uses: 'actions/setup-python@v2'
        with:
          python-version: '3.7'

      - uses: './.github/actions/python/setup'
        with:
          project: 'update-server'
      - name: Lint
        run: make -C update-server lint
  test:
    name: 'update server package tests'
    timeout-minutes: 10
    needs: [lint]
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v1'
        with:
          node-version: '12'
      - uses: 'actions/setup-python@v2'
        with:
          python-version: '3.7'
      - uses: './.github/actions/python/setup'
        with:
          project: 'update-server'
      - name: Test
        run: make -C update-server test
      - uses: 'codecov/codecov-action@v2'
        with:
          files: ./update-server/coverage.xml
          flags: update-server
